"""Cities offered in the search box: display name, state, and the spellings used to recognise them in job locations.

About 100 places with office jobs: metros, state capitals and industrial/IT hubs. Cities not listed can still be typed.
"""
CITIES = [
    # Metros and NCR
    ("Delhi", "Delhi", ["new delhi", "delhi"]),
    ("Gurugram", "Haryana", ["gurugram", "gurgaon"]),
    ("Noida", "Uttar Pradesh", ["noida"]),
    ("Ghaziabad", "Uttar Pradesh", ["ghaziabad"]),
    ("Faridabad", "Haryana", ["faridabad"]),
    ("Mumbai", "Maharashtra", ["mumbai", "bombay"]),
    ("Navi Mumbai", "Maharashtra", ["navi mumbai"]),
    ("Thane", "Maharashtra", ["thane"]),
    ("Pune", "Maharashtra", ["pune"]),
    ("Bengaluru", "Karnataka", ["bengaluru", "bangalore"]),
    ("Hyderabad", "Telangana", ["hyderabad", "secunderabad"]),
    ("Chennai", "Tamil Nadu", ["chennai", "madras"]),
    ("Kolkata", "West Bengal", ["kolkata", "calcutta"]),
    ("Ahmedabad", "Gujarat", ["ahmedabad"]),
    # Rajasthan
    ("Jaipur", "Rajasthan", ["jaipur"]),
    ("Jodhpur", "Rajasthan", ["jodhpur"]),
    ("Udaipur", "Rajasthan", ["udaipur"]),
    ("Kota", "Rajasthan", ["kota"]),
    ("Ajmer", "Rajasthan", ["ajmer"]),
    ("Bikaner", "Rajasthan", ["bikaner"]),
    ("Alwar", "Rajasthan", ["alwar"]),
    ("Bhiwadi", "Rajasthan", ["bhiwadi"]),
    # Gujarat
    ("Gandhinagar", "Gujarat", ["gandhinagar"]),
    ("Vadodara", "Gujarat", ["vadodara", "baroda"]),
    ("Surat", "Gujarat", ["surat"]),
    ("Rajkot", "Gujarat", ["rajkot"]),
    ("Vapi", "Gujarat", ["vapi"]),
    ("Bharuch", "Gujarat", ["bharuch"]),
    ("Jamnagar", "Gujarat", ["jamnagar"]),
    # Madhya Pradesh and Chhattisgarh
    ("Indore", "Madhya Pradesh", ["indore"]),
    ("Bhopal", "Madhya Pradesh", ["bhopal"]),
    ("Gwalior", "Madhya Pradesh", ["gwalior"]),
    ("Jabalpur", "Madhya Pradesh", ["jabalpur"]),
    ("Raipur", "Chhattisgarh", ["raipur"]),
    ("Bhilai", "Chhattisgarh", ["bhilai"]),
    # Uttar Pradesh
    ("Lucknow", "Uttar Pradesh", ["lucknow"]),
    ("Kanpur", "Uttar Pradesh", ["kanpur"]),
    ("Agra", "Uttar Pradesh", ["agra"]),
    ("Varanasi", "Uttar Pradesh", ["varanasi"]),
    ("Prayagraj", "Uttar Pradesh", ["prayagraj", "allahabad"]),
    ("Meerut", "Uttar Pradesh", ["meerut"]),
    ("Bareilly", "Uttar Pradesh", ["bareilly"]),
    # Punjab, Haryana, Chandigarh
    ("Chandigarh", "Chandigarh", ["chandigarh"]),
    ("Mohali", "Punjab", ["mohali"]),
    ("Panchkula", "Haryana", ["panchkula"]),
    ("Ludhiana", "Punjab", ["ludhiana"]),
    ("Amritsar", "Punjab", ["amritsar"]),
    ("Jalandhar", "Punjab", ["jalandhar"]),
    ("Panipat", "Haryana", ["panipat"]),
    ("Sonipat", "Haryana", ["sonipat", "sonepat"]),
    ("Manesar", "Haryana", ["manesar"]),
    # Uttarakhand, Himachal, Jammu and Kashmir
    ("Dehradun", "Uttarakhand", ["dehradun"]),
    ("Haridwar", "Uttarakhand", ["haridwar"]),
    ("Rudrapur", "Uttarakhand", ["rudrapur"]),
    ("Shimla", "Himachal Pradesh", ["shimla"]),
    ("Baddi", "Himachal Pradesh", ["baddi"]),
    ("Jammu", "Jammu and Kashmir", ["jammu"]),
    ("Srinagar", "Jammu and Kashmir", ["srinagar"]),
    # East and North-East
    ("Patna", "Bihar", ["patna"]),
    ("Ranchi", "Jharkhand", ["ranchi"]),
    ("Jamshedpur", "Jharkhand", ["jamshedpur"]),
    ("Dhanbad", "Jharkhand", ["dhanbad"]),
    ("Bhubaneswar", "Odisha", ["bhubaneswar"]),
    ("Cuttack", "Odisha", ["cuttack"]),
    ("Rourkela", "Odisha", ["rourkela"]),
    ("Durgapur", "West Bengal", ["durgapur"]),
    ("Siliguri", "West Bengal", ["siliguri"]),
    ("Howrah", "West Bengal", ["howrah"]),
    ("Guwahati", "Assam", ["guwahati"]),
    # Maharashtra and Goa
    ("Nagpur", "Maharashtra", ["nagpur"]),
    ("Nashik", "Maharashtra", ["nashik"]),
    ("Aurangabad", "Maharashtra", ["chhatrapati sambhajinagar", "aurangabad"]),
    ("Kolhapur", "Maharashtra", ["kolhapur"]),
    ("Solapur", "Maharashtra", ["solapur"]),
    ("Goa", "Goa", ["goa", "panaji"]),
    # Karnataka and Kerala
    ("Mysuru", "Karnataka", ["mysuru", "mysore"]),
    ("Mangaluru", "Karnataka", ["mangaluru", "mangalore"]),
    ("Hubballi", "Karnataka", ["hubballi", "hubli"]),
    ("Belagavi", "Karnataka", ["belagavi", "belgaum"]),
    ("Kochi", "Kerala", ["kochi", "cochin"]),
    ("Thiruvananthapuram", "Kerala", ["thiruvananthapuram", "trivandrum"]),
    ("Kozhikode", "Kerala", ["kozhikode", "calicut"]),
    ("Thrissur", "Kerala", ["thrissur"]),
    # Tamil Nadu and Puducherry
    ("Coimbatore", "Tamil Nadu", ["coimbatore"]),
    ("Madurai", "Tamil Nadu", ["madurai"]),
    ("Tiruchirappalli", "Tamil Nadu", ["tiruchirappalli", "trichy"]),
    ("Salem", "Tamil Nadu", ["salem"]),
    ("Hosur", "Tamil Nadu", ["hosur"]),
    ("Tiruppur", "Tamil Nadu", ["tiruppur", "tirupur"]),
    ("Vellore", "Tamil Nadu", ["vellore"]),
    ("Puducherry", "Puducherry", ["puducherry", "pondicherry"]),
    # Andhra Pradesh and Telangana
    ("Visakhapatnam", "Andhra Pradesh", ["visakhapatnam", "vizag"]),
    ("Vijayawada", "Andhra Pradesh", ["vijayawada"]),
    ("Guntur", "Andhra Pradesh", ["guntur"]),
    ("Tirupati", "Andhra Pradesh", ["tirupati"]),
    ("Nellore", "Andhra Pradesh", ["nellore"]),
    ("Warangal", "Telangana", ["warangal"]),
]
